# Copyright 2021 Amazon.com, Inc. or its affiliates. All Rights Reserved.
#
# Builders
# Carlos Ramos: @carrams

AWSTemplateFormatVersion: "2010-09-09"
Description: "CloudFront distribution for BRH. The source is the S3 bucket with the web files for the BRH admin portal."

Parameters:
  AcmCertificate:
    Type: String
    Description: ARN of ACM Certificate

  WebsiteBucketName:
    Description: "Name of the bucket where the website files will live"
    Type: String

  DomainName:
    Description: Primary domain name for the distribution. Example. mydomain.com
    Type: String
    Default: "tls-endpoint.com"

  AlternateDomainName:
    Description: "Alternate domain name. Example: www.mydomain.com"
    Type: String
    Default: "www.tls-endpoint.com"

  DefaultTTL:
    Description: The default time in seconds that objects stay in CloudFront caches before CloudFront forwards another request to your custom origin. By default, AWS CloudFormation specifies 86400 seconds (one day).
    Type: String
    Default: "0"

  MaxTTL:
    Description: The maximum time in seconds that objects stay in CloudFront caches before CloudFront forwards another request to your custom origin. By default, AWS CloudFormation specifies 31536000 seconds (one year).
    Type: String
    Default: "0"

  MinTTL:
    Description: The minimum amount of time that you want objects to stay in the cache before CloudFront queries your origin to see whether the object has been updated.
    Type: String
    Default: "0"

  PriceClass:
    Description: The price class that corresponds with the maximum price that you want to pay for CloudFront service. If you specify PriceClass_All, CloudFront responds to requests for your objects from all CloudFront edge locations.
    Type: String
    Default: "PriceClass_All"
    AllowedValues:
      - PriceClass_All
      - PriceClass_100
      - PriceClass_200

  DnsTTL:
    Description: Route53 Record Set TTL
    Type: Number
    Default: 600

Resources:
  # #ROUTE 53 HOSTED ZONE
  # Route53HostedZone:
  #   Type: AWS::Route53::HostedZone
  #   Properties:
  #     Name: !Ref DomainName

  # #ROUTE 53 RECORD SETS
  # Route53RecordSetGroup:
  #   Type: AWS::Route53::RecordSetGroup
  #   DependsOn: CloudFrontDistribution
  #   Properties:
  #     HostedZoneName: !Sub "${DomainName}."
  #     RecordSets:
  #       - Name: !Sub "${AlternateDomainName}"
  #         Type: "A"
  #         AliasTarget:
  #           DNSName: !GetAtt "CloudFrontDistribution.DomainName"
  #           EvaluateTargetHealth: false
  #           # The  following HosteZoneId is always used for alias records pointing to CF.
  #           HostedZoneId: "Z2FDTNDATAQYW2"

  # ApexRoute53RecordSetGroup:
  #   Type: AWS::Route53::RecordSetGroup
  #   DependsOn: CloudFrontDistribution
  #   Properties:
  #     HostedZoneName: !Sub "${DomainName}."
  #     RecordSets:
  #       - Name: !Ref "DomainName"
  #         Type: "A"
  #         AliasTarget:
  #           DNSName: !GetAtt "CloudFrontDistribution.DomainName"
  #           EvaluateTargetHealth: false
  #           # The  following HosteZoneId is always used for alias records pointing to CF.
  #           HostedZoneId: "Z2FDTNDATAQYW2"

  #ACM CERTIFICATE
  # AcmCertificate:
  #   Type: AWS::CertificateManager::Certificate
  #   DependsOn: Route53HostedZone
  #   Properties:
  #     DomainName: !Sub "*.${DomainName}"
  #     ValidationMethod: DNS
  #     DomainValidationOptions:
  #       - DomainName: !Ref DomainName
  #         HostedZoneId: !Ref Route53HostedZone

  #S3 WEBSITE BUCKET
  # S3WebsiteBucket:
  #   Type: "AWS::S3::Bucket"
  #   DependsOn: CloudFrontOAI
  #   Properties:
  #     BucketName: !Ref WebsiteBucketName

  #S3 WEBSITE BUCKET POLICY
  S3WebsiteBucketPolicy:
    Type: "AWS::S3::BucketPolicy"
    Properties:
      Bucket: !Ref WebsiteBucketName
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Sid: WebsiteBucketPermissions
            Effect: "Allow"
            Principal:
              AWS: !Sub "arn:aws:iam::cloudfront:user/CloudFront Origin Access Identity ${CloudFrontOAI}"
            Action: "s3:GetObject"
            Resource: !Sub arn:aws:s3:::${WebsiteBucketName}/*

  #CLOUDFRONT ORIGIN ACCESS IDENTITY
  CloudFrontOAI:
    Type: AWS::CloudFront::CloudFrontOriginAccessIdentity
    Properties:
      CloudFrontOriginAccessIdentityConfig:
        Comment: "CloudFront OAI for BRH Domain"

  # CLOUDFRONT DISTRIBUTION
  CloudFrontDistribution:
    Type: "AWS::CloudFront::Distribution"
    DependsOn: CloudFrontOAI
    Properties:
      DistributionConfig:
        #Important: these error codes enable the React router to respond with the index page in case the user refreshes
        #the browser. As long as the index page is returned, routing will occur in the browser.
        CustomErrorResponses:
          - ErrorCode: 400
            ResponsePagePath: "/index.html"
            ResponseCode: 400
            ErrorCachingMinTTL: 10
          - ErrorCode: 403
            ResponsePagePath: "/index.html"
            ResponseCode: 403
            ErrorCachingMinTTL: 10
        Comment: "Cloudfront Distribution for BRH"
        Origins:
          - DomainName: !Sub "${WebsiteBucketName}.s3.amazonaws.com"
            Id: !Ref WebsiteBucketName
            OriginPath: ""
            S3OriginConfig:
              OriginAccessIdentity: !Sub "origin-access-identity/cloudfront/${CloudFrontOAI}"
        Enabled: true
        HttpVersion: "http2"
        Aliases:
          - !Ref DomainName
        DefaultRootObject: "index.html"
        DefaultCacheBehavior:
          AllowedMethods:
            - GET
            - HEAD
            - DELETE
            - OPTIONS
            - PATCH
            - POST
            - PUT
          Compress: True
          DefaultTTL: !Ref "DefaultTTL"
          MaxTTL: !Ref "MaxTTL"
          MinTTL: !Ref "MinTTL"
          SmoothStreaming: "false"
          TargetOriginId: !Ref WebsiteBucketName
          ViewerProtocolPolicy: "redirect-to-https"
          ForwardedValues:
            QueryString: False
        PriceClass: !Ref PriceClass
        ViewerCertificate:
          AcmCertificateArn: !Ref AcmCertificate
          SslSupportMethod: "sni-only"
          MinimumProtocolVersion: "TLSv1.1_2016"
        IPV6Enabled: True
